import type { EmojiCategory, EmojiEntry } from './emoji-catalog-core';

export const EMOJI_ICON_CATEGORIES: EmojiCategory[] = [
    {
        id: 'documents',
        labelKey: 'folders.icon_category.documents',
        entries: [
            { char: '📁', keys: 'folder directory 文件夹 目录 归档' },
            { char: '📂', keys: 'open folder expand 打开文件夹 展开' },
            { char: '🗂️', keys: 'dividers archive index 档案盒 分类 卷宗' },
            { char: '🗃️', keys: 'file box archive store 档案箱 收纳' },
            { char: '🗄️', keys: 'cabinet filing db 文件柜 归档 数据库' },
            { char: '📄', keys: 'page document file 页面 文档 单页' },
            { char: '📃', keys: 'page curl draft 卷角 草稿' },
            { char: '📑', keys: 'tabs bookmark dividers 分页签 标签页' },
            { char: '📜', keys: 'scroll long text legacy 卷轴 长文 历史' },
            { char: '🧾', keys: 'receipt invoice bill list 收据 发票 账单 清单' },
            { char: '📰', keys: 'news press article 报纸 资讯 文章' },
            { char: '🗞️', keys: 'rolled news briefing 报纸卷 简报' },
            { char: '📋', keys: 'clipboard checklist 剪贴板 待办 清单' },
            { char: '📌', keys: 'pin sticky note 图钉 置顶 便签' },
            { char: '📍', keys: 'pin location map 定位 地标 位置' },
            { char: '🔖', keys: 'bookmark save later 书签 收藏' },
            { char: '📎', keys: 'paperclip attachment 回形针 附件' },
            { char: '🖇️', keys: 'linked clips chain 链接 回形针' },
            { char: '✂️', keys: 'cut scissors clip 剪切 剪刀' },
            { char: '📐', keys: 'ruler triangle spec 三角尺 规格' },
            { char: '📏', keys: 'ruler length measure 直尺 长度' },
            { char: '🗒️', keys: 'notepad notes 便签本 备忘' },
            { char: '📝', keys: 'memo writing note 备忘 记录 写作' },
            { char: '✍️', keys: 'sign writing hand 签名 手写' },
            { char: '✏️', keys: 'pencil edit draft 铅笔 编辑 草稿' },
            { char: '🖊️', keys: 'pen write 钢笔 书写' },
            { char: '🖋️', keys: 'fountain pen sign 签字笔 契约' },
            { char: '🔏', keys: 'lock pen privacy 加密 签名' },
            { char: '📓', keys: 'notebook journal 笔记本 日志' },
            { char: '📔', keys: 'notebook decorated 日记本 手账' },
            { char: '📒', keys: 'ledger accounts 账本 台账' },
            { char: '📕', keys: 'book closed manual 手册 合书' },
            { char: '📖', keys: 'open book read 阅读 打开的书' },
            { char: '📘', keys: 'blue book spec 蓝皮书 规范' },
            { char: '📗', keys: 'green book guide 绿皮书 指南' },
            { char: '📙', keys: 'orange book textbook 橙皮书 教材' },
            { char: '📚', keys: 'books library stack study 书籍 书架 资料 学习 参考' },
            { char: '🗑️', keys: 'trash bin delete 垃圾桶 删除' },
            { char: '📦', keys: 'package box parcel 包裹 归档 发布包' },
            { char: '🔅', keys: 'brightness low 调暗' },
        ],
    },
    {
        id: 'development',
        labelKey: 'folders.icon_category.development',
        entries: [
            { char: '💻', keys: 'laptop code dev 电脑 编程 开发' },
            { char: '🖥️', keys: 'desktop workstation 台式机 工作站' },
            { char: '🖱️', keys: 'mouse click 鼠标 点击' },
            { char: '⌨️', keys: 'keyboard typing 键盘 输入' },
            { char: '🖨️', keys: 'printer print pdf 打印机 导出' },
            { char: '💾', keys: 'save floppy disk 保存 存盘' },
            { char: '📀', keys: 'disc cd dvd 光盘 镜像' },
            { char: '💿', keys: 'cd rom disc 光盘' },
            { char: '🔌', keys: 'plug plugin power 插件 插头' },
            { char: '🔋', keys: 'battery power 电池 电量' },
            { char: '📡', keys: 'antenna api stream 卫星 接口' },
            { char: '🕸️', keys: 'web crawler net 爬虫 网络' },
            { char: '🌐', keys: 'globe web i18n 网络 全球化' },
            { char: '🔗', keys: 'link url chain 链接 关联' },
            { char: '🔒', keys: 'lock private secure 锁 私密' },
            { char: '🔓', keys: 'unlock public 解锁 公开' },
            { char: '🔑', keys: 'key secret token 密钥 令牌' },
            { char: '🗝️', keys: 'old key legacy 老钥匙' },
            { char: '🛡️', keys: 'shield security guard 安全 防护' },
            { char: '🐛', keys: 'bug defect issue 缺陷 bug' },
            { char: '🧪', keys: 'test lab trial 测试 实验' },
            { char: '🔬', keys: 'microscope science lab debug research 调试 研究 科学 实验室' },
            { char: '⚙️', keys: 'gear settings config 设置 齿轮 配置' },
            { char: '🔧', keys: 'wrench fix tool 扳手 修复' },
            { char: '🔨', keys: 'hammer build 锤子 构建' },
            { char: '🛠️', keys: 'tools kit repair 工具箱 维护' },
            { char: '⛏️', keys: 'pick mine dig 挖矿 采掘' },
            { char: '🧲', keys: 'magnet pull fetch 磁铁 抓取' },
            { char: '🗜️', keys: 'compress zip clamp 压缩 打包' },
            { char: '🧱', keys: 'brick module block 砖 模块' },
            { char: '🏗️', keys: 'crane scaffold wip 施工 脚手架' },
            { char: '🚦', keys: 'traffic light ci pipeline 流水线 信号' },
            { char: '🚧', keys: 'barrier wip under construction 施工中 屏障' },
            { char: '📶', keys: 'signal bars wifi 信号 网络' },
            { char: '🔦', keys: 'flashlight inspect 手电 排查' },
            { char: '🧯', keys: 'extinguisher incident 灭火 事故' },
            { char: '💡', keys: 'idea bulb tip insight 想法 点子 灵感' },
            { char: '🧠', keys: 'brain mind ai model 大脑 模型 智能 心智 知识' },
            { char: '🤖', keys: 'robot ai bot agent avatar 机器人 智能体 头像' },
            { char: '📈', keys: 'chart up growth metric 增长 指标' },
            { char: '📉', keys: 'chart down drop 下降 下跌' },
            { char: '📊', keys: 'bar chart stats 柱状图 统计' },
            { char: '🗜', keys: 'clamp squeeze 夹紧' },
            { char: '🔍', keys: 'search find inspect 搜索 查找' },
            { char: '🔎', keys: 'zoom search inspect 放大 排查' },
            { char: '🧮', keys: 'abacus calc count 算盘 计算' },
            { char: '⏱️', keys: 'stopwatch perf timing 计时 性能' },
            { char: '⏳', keys: 'hourglass pending 等待 沙漏' },
            { char: '⌛', keys: 'hourless done timer 计时结束' },
            { char: '🌀', keys: 'cyclone loop spin 循环 旋涡' },
            { char: '♻️', keys: 'recycle refactor refresh 回收 重构' },
            { char: '🔄', keys: 'sync refresh arrows 同步 刷新' },
            { char: '🔁', keys: 'repeat loop 循环 重复' },
            { char: '🔀', keys: 'shuffle merge branch 分支 合并' },
            { char: '⚡', keys: 'zap fast energy 闪电 加速' },
            { char: '🚀', keys: 'rocket launch ship 火箭 上线 发布' },
            { char: '🛰️', keys: 'satellite edge cloud 卫星 边缘' },
            { char: '🧿', keys: 'nazar protect 护符' },
        ],
    },
    {
        id: 'languages',
        labelKey: 'folders.icon_category.languages',
        entries: [
            { char: '🐍', keys: 'python snake 蟒蛇 蛇' },
            { char: '🦀', keys: 'rust crab 螃蟹 锈' },
            { char: '🐹', keys: 'go golang hamster 仓鼠' },
            { char: '🐘', keys: 'php postgres elephant 大象' },
            { char: '💎', keys: 'ruby gem diamond 红宝石 宝石' },
            { char: '🟨', keys: 'javascript js yellow 黄块' },
            { char: '🔷', keys: 'typescript ts blue diamond 蓝钻' },
            { char: '🔹', keys: 'small blue diamond ts 小蓝钻' },
            { char: '🟦', keys: 'blue square block 蓝块' },
            { char: '🟩', keys: 'green square pass 绿块' },
            { char: '🟥', keys: 'red square fail 红块' },
            { char: '🟪', keys: 'purple square 紫块' },
            { char: '⚛️', keys: 'atom react atomic 原子' },
            { char: '🐧', keys: 'linux penguin os 企鹅 系统' },
            { char: '🐳', keys: 'docker whale container 鲸鱼 容器' },
            { char: '🦊', keys: 'firefox fox 狐狸' },
            { char: '🪶', keys: 'feather swift light 羽毛 轻' },
            { char: '🦆', keys: 'duck query 鸭子' },
            { char: '🐪', keys: 'camel case 骆驼' },
            { char: '🛢️', keys: 'drum db sql store 油桶 数据库' },
            { char: '🔤', keys: 'letters abc input 字母 输入' },
            { char: '🔢', keys: 'numbers input 数字 输入' },
            { char: '🔣', keys: 'symbols input 符号 输入' },
            { char: '🅰️', keys: 'a button letter 字母 a' },
            { char: '🆎', keys: 'ab button blood 字母 ab' },
            { char: '🅾️', keys: 'o button letter 字母 o' },
            { char: '🆑', keys: 'cl button clear 清除' },
            { char: '🆔', keys: 'id identity 标识 id' },
            { char: '🆚', keys: 'versus compare 对比 vs' },
            { char: '🈁', keys: 'here japanese 此处' },
            { char: '🈯', keys: 'pointed japanese 指' },
            { char: '🈳', keys: 'vacancy japanese 空位' },
            { char: '🈂️', keys: 'service japanese 服务' },
            { char: '🔠', keys: 'latin letters uppercase 大写字母' },
            { char: '🔡', keys: 'latin letters lowercase 小写字母' },
        ],
    },
    {
        id: 'work',
        labelKey: 'folders.icon_category.work',
        entries: [
            { char: '💼', keys: 'briefcase work job 公文包 工作 商务' },
            { char: '👔', keys: 'tie office job 领带 职场' },
            { char: '🏢', keys: 'office building company 公司 办公楼' },
            { char: '🏭', keys: 'factory plant 工厂' },
            { char: '🏦', keys: 'bank finance 银行 金融' },
            { char: '🏥', keys: 'hospital health 医院 健康' },
            { char: '🏫', keys: 'school class 学校 课堂' },
            { char: '🏛️', keys: 'classic law museum 学院 法务' },
            { char: '⚖️', keys: 'scales law balance 法律 平衡' },
            { char: '📇', keys: 'card index contacts 名片 索引' },
            { char: '📅', keys: 'calendar date schedule 日历 日程' },
            { char: '📆', keys: 'tear off calendar 台历' },
            { char: '🗓️', keys: 'spiral calendar month 日历本 排期' },
            { char: '⏰', keys: 'alarm clock deadline 闹钟 截止' },
            { char: '⏲️', keys: 'timer clock 计时器' },
            { char: '🕐', keys: 'clock one time 时间 点钟' },
            { char: '📣', keys: 'megaphone announce 喇叭 公告' },
            { char: '📢', keys: 'loudspeaker broadcast 广播 通知' },
            { char: '📞', keys: 'phone call 电话 来电' },
            { char: '☎️', keys: 'telephone landline 座机' },
            { char: '📟', keys: 'pager oncall 寻呼 值班' },
            { char: '📠', keys: 'fax machine 传真' },
            { char: '🖇', keys: 'clips together 别针' },
            { char: '🎯', keys: 'target goal okr 目标 命中' },
            { char: '🏆', keys: 'trocup winner award 奖杯 冠军' },
            { char: '🏅', keys: 'medal prize 奖牌' },
            { char: '🥇', keys: 'gold medal first 金牌 第一' },
            { char: '🎖️', keys: 'military medal honor 勋章' },
            { char: '🔔', keys: 'bell notify 铃 提醒' },
            { char: '🔕', keys: 'bell off mute 静音 免打扰' },
            { char: '🈹', keys: 'discount japanese 折扣' },
        ],
    },
    {
        id: 'travel',
        labelKey: 'folders.icon_category.travel',
        entries: [
            { char: '✈️', keys: 'plane flight travel 飞机 航班 出行' },
            { char: '🛩️', keys: 'small plane 小飞机' },
            { char: '🚁', keys: 'helicopter 直升机' },
            { char: '🛸', keys: 'ufo unknown 飞碟' },
            { char: '🚄', keys: 'bullet train rail 高铁 动车' },
            { char: '🚂', keys: 'steam train 蒸汽火车' },
            { char: '🚆', keys: 'train railway 火车 铁路' },
            { char: '🚇', keys: 'metro subway 地铁' },
            { char: '🚌', keys: 'bus coach 巴士 公交' },
            { char: '🚑', keys: 'ambulance emergency 救护 急救' },
            { char: '🚒', keys: 'fire engine 消防车' },
            { char: '🚓', keys: 'police car 警车' },
            { char: '🚗', keys: 'car drive 汽车 自驾' },
            { char: '🚕', keys: 'taxi cab 出租' },
            { char: '🚙', keys: 'suv vehicle SUV 越野' },
            { char: '🏍️', keys: 'motorbike 摩托' },
            { char: '🚲', keys: 'bike cycle 自行车 骑行' },
            { char: '🛵', keys: 'scooter delivery 踏板车 外卖' },
            { char: '🛶', keys: 'canoe boat 独木舟' },
            { char: '⛵', keys: 'sailboat yacht 帆船 游艇' },
            { char: '🚤', keys: 'speedboat 快艇' },
            { char: '🛳️', keys: 'cruise ship 邮轮' },
            { char: '⛴️', keys: 'ferry 渡轮' },
            { char: '🚢', keys: 'ship boat 轮船' },
            { char: '🗺️', keys: 'map world travel 地图 世界' },
            { char: '🧭', keys: 'compass direction 指南针 方向' },
            { char: '🏔️', keys: 'snow mountain hike 雪山 徒步' },
            { char: '⛰️', keys: 'mountain 山峰' },
            { char: '🌋', keys: 'volcano 火山' },
            { char: '🏕️', keys: 'camping tent 露营' },
            { char: '⛺', keys: 'tent camp 帐篷' },
            { char: '🏖️', keys: 'beach umbrella 海滩 度假' },
            { char: '🏝️', keys: 'desert island 海岛' },
            { char: '🗻', keys: 'fuji mountain 富士山' },
            { char: '🏯', keys: 'japanese castle 日本城 古迹' },
            { char: '🏰', keys: 'castle 城堡' },
            { char: '⛪', keys: 'church 教堂' },
            { char: '🕌', keys: 'mosque 清真寺' },
            { char: '🕍', keys: 'synagogue 犹太会堂' },
            { char: '⛩️', keys: 'torii shrine 鸟居 神社' },
            { char: '🗽', keys: 'liberty statue 自由女神' },
            { char: '🗼', keys: 'tower tokyo 塔 东京' },
            { char: '🗿', keys: 'moai stone 石像' },
            { char: '🎡', keys: 'ferris wheel park 摩天轮' },
            { char: '🎢', keys: 'roller coaster 过山车' },
            { char: '🎫', keys: 'ticket pass 门票 票' },
            { char: '🛂', keys: 'passport control 出入境 护照' },
            { char: '🧳', keys: 'luggage suitcase 行李 行李箱' },
            { char: '🏨', keys: 'hotel stay 酒店 住宿' },
            { char: '🚩', keys: 'triangular flag 旗 里程碑' },
            { char: '🎌', keys: 'crossed flags 国旗 国际' },
            { char: '🌄', keys: 'sunrise mountains 日出' },
            { char: '🌅', keys: 'sunrise 清晨' },
            { char: '🌃', keys: 'night stars 夜景' },
        ],
    },
    {
        id: 'shopping',
        labelKey: 'folders.icon_category.shopping',
        entries: [
            { char: '🛒', keys: 'cart shop buy 购物车 采购' },
            { char: '🛍️', keys: 'shopping bags retail 购物袋 零售' },
            { char: '🎁', keys: 'gift present 礼物 赠品' },
            { char: '🎀', keys: 'ribbon bow gift 丝带 礼品' },
            { char: '🛎️', keys: 'bell hotel service 服务铃' },
            { char: '🏷️', keys: 'label tag price 标签 价格' },
            { char: '💰', keys: 'money bag cash 钱袋 资金' },
            { char: '💵', keys: 'dollar bill cash 美元 现金' },
            { char: '💴', keys: 'yen bill 日元' },
            { char: '💶', keys: 'euro bill 欧元' },
            { char: '💷', keys: 'pound bill 英镑' },
            { char: '💸', keys: 'money wings spend 花钱 支出' },
            { char: '🪙', keys: 'coin change 硬币 零钱' },
            { char: '💳', keys: 'card payment credit 信用卡 支付' },
            { char: '🧧', keys: 'red envelope bonus 红包' },
            { char: '💹', keys: 'chart yen market 行情 交易' },
            { char: '💲', keys: 'heavy dollar 金额' },
            { char: '🏧', keys: 'atm withdraw 取款' },
            { char: '🚚', keys: 'delivery truck ship 配送 物流' },
            { char: '🏪', keys: 'convenience store shop open retail 便利店 商店' },
            { char: '🏬', keys: 'department store 百货' },
            { char: '⭐', keys: 'star rate favorite 星标 评分 收藏' },
            { char: '🌟', keys: 'glowing star top 亮星 精选' },
        ],
    },
    {
        id: 'people',
        labelKey: 'folders.icon_category.people',
        entries: [
            { char: '👤', keys: 'user person profile 用户 个人' },
            { char: '👥', keys: 'users team group 团队 用户组' },
            { char: '🧑', keys: 'person adult 人 成人' },
            { char: '👨', keys: 'man male 男人' },
            { char: '👩', keys: 'woman female 女人' },
            { char: '👦', keys: 'boy 男孩' },
            { char: '👧', keys: 'girl 女孩' },
            { char: '🧒', keys: 'child kid 儿童' },
            { char: '👶', keys: 'baby infant 婴儿 宝宝' },
            { char: '🧓', keys: 'older person elder 长者' },
            { char: '👴', keys: 'old man 老人' },
            { char: '👵', keys: 'old woman 老奶奶' },
            { char: '👮', keys: 'police officer 警察 执法' },
            { char: '🕵️', keys: 'detective investigate 侦探 调查' },
            { char: '👷', keys: 'worker engineer 工人 工程师' },
            { char: '💂', keys: 'guard 卫兵 守卫' },
            { char: '🎅', keys: 'santa xmas 圣诞' },
            { char: '👸', keys: 'princess 公主' },
            { char: '🤴', keys: 'prince 王子' },
            { char: '👑', keys: 'crown king vip 王冠 尊贵' },
            { char: '🎓', keys: 'graduate degree 毕业 学历' },
            { char: '🤝', keys: 'handshake deal 合作 握手' },
            { char: '👏', keys: 'clap applause 鼓掌 好评' },
            { char: '🙌', keys: 'raise hands celebrate 庆祝 双手' },
            { char: '🙏', keys: 'pray thanks 感谢 祈祷' },
            { char: '💪', keys: 'strong muscle power 力量 加油' },
            { char: '👀', keys: 'eyes watch 关注 查看' },
            { char: '🗣️', keys: 'speak talk 发言 演讲' },
            { char: '👻', keys: 'ghost spooky 幽灵 隐藏' },
            { char: '🎃', keys: 'pumpkin halloween 南瓜 万圣' },
            { char: '😀', keys: 'grin happy 开心 大笑' },
            { char: '🙂', keys: 'smile ok 微笑 还行' },
            { char: '😐', keys: 'neutral 中立 无感' },
            { char: '😢', keys: 'cry sad 难过 哭泣' },
            { char: '😡', keys: 'angry rage 生气 告警' },
            { char: '😎', keys: 'cool sunglasses 酷' },
            { char: '🤔', keys: 'think hmm 思考 存疑' },
            { char: '😴', keys: 'sleep zzz 休眠 睡觉' },
            { char: '🥳', keys: 'party celebrate 派对 庆祝' },
            { char: '😱', keys: 'shock alert 惊吓 告警' },
        ],
    },
    {
        id: 'learning',
        labelKey: 'folders.icon_category.learning',
        entries: [
            { char: '🎨', keys: 'art design palette 美术 设计 配色' },
            { char: '🖌️', keys: 'brush paint 画笔 绘画' },
            { char: '🖼️', keys: 'picture frame gallery 图片 画廊 相框' },
            { char: '🎭', keys: 'theater drama 戏剧 表演' },
            { char: '🎬', keys: 'clapper video film 视频 影片' },
            { char: '🎥', keys: 'movie camera record 摄像机 录制' },
            { char: '📷', keys: 'camera photo 相机 照片' },
            { char: '📸', keys: 'flash photo 拍照' },
            { char: '🎤', keys: 'mic podcast 麦克风 播客' },
            { char: '🎧', keys: 'headphone audio 耳机 音频' },
            { char: '🎼', keys: 'score music 乐谱 作曲' },
            { char: '🎵', keys: 'note music 音符 音乐' },
            { char: '🎶', keys: 'notes tune 旋律' },
            { char: '🎹', keys: 'piano keyboard 钢琴 键盘' },
            { char: '🥁', keys: 'drum beat 鼓 节奏' },
            { char: '🎸', keys: 'guitar 吉他' },
            { char: '🎺', keys: 'trumpet 小号' },
            { char: '🎻', keys: 'violin 小提琴' },
            { char: '🎮', keys: 'game play 游戏 玩' },
            { char: '🕹️', keys: 'joystick retro 摇杆 复古' },
            { char: '👾', keys: 'pixel monster 像素 怪兽' },
            { char: '🎲', keys: 'dice random 骰子 随机' },
            { char: '♟️', keys: 'chess strategy 棋 策略' },
            { char: '🧩', keys: 'puzzle piece module 拼图 模块' },
            { char: '✒️', keys: 'nib write 笔尖 著述' },
            { char: '🏺', keys: 'amphora artifact 文物 古董' },
            { char: '📯', keys: 'post horn 号角 传讯' },
        ],
    },
    {
        id: 'nature',
        labelKey: 'folders.icon_category.nature',
        entries: [
            { char: '🌱', keys: 'seedling grow new 幼苗 生长 新增' },
            { char: '🌿', keys: 'herb green 草药 绿枝' },
            { char: '☘️', keys: 'shamrock luck 三叶草 幸运' },
            { char: '🍀', keys: 'four leaf luck 四叶草 幸运' },
            { char: '🍁', keys: 'maple autumn fall 枫叶 秋天' },
            { char: '🍂', keys: 'fallen leaf 落叶' },
            { char: '🍃', keys: 'leaves wind 飘叶 风' },
            { char: '🌲', keys: 'pine evergreen 松树 常绿' },
            { char: '🌳', keys: 'tree 大树 树' },
            { char: '🌴', keys: 'palm vacation 棕榈 热带' },
            { char: '🌵', keys: 'cactus desert 仙人掌 沙漠' },
            { char: '🎄', keys: 'christmas tree 圣诞树' },
            { char: '🌸', keys: 'cherry blossom spring 樱花 春天' },
            { char: '💮', keys: 'white flower 白花' },
            { char: '🏵️', keys: 'rosette badge 花章 徽章' },
            { char: '🌹', keys: 'rose love 玫瑰' },
            { char: '🌷', keys: 'tulip 郁金香' },
            { char: '🌻', keys: 'sunflower 向日葵' },
            { char: '🌼', keys: 'blossom 小花' },
            { char: '🍄', keys: 'mushroom 蘑菇' },
            { char: '🌾', keys: 'rice harvest 稻穗 丰收' },
            { char: '🐝', keys: 'bee hive 蜜蜂' },
            { char: '🦋', keys: 'butterfly 蝴蝶' },
            { char: '🐌', keys: 'snail slow 蜗牛 慢' },
            { char: '🐞', keys: 'ladybug beetle 瓢虫' },
            { char: '🐜', keys: 'ant tiny 蚂蚁' },
            { char: '🕷️', keys: 'spider 蜘蛛' },
            { char: '🐠', keys: 'tropical fish 热带鱼' },
            { char: '🐟', keys: 'fish 鱼' },
            { char: '🐬', keys: 'dolphin 海豚' },
            { char: '🐋', keys: 'whale big 鲸鱼' },
            { char: '🦈', keys: 'shark 鲨鱼' },
            { char: '🐢', keys: 'turtle slow 乌龟 慢' },
            { char: '🦉', keys: 'owl wisdom 猫头鹰 夜间' },
            { char: '🦅', keys: 'eagle 鹰' },
            { char: '🐦', keys: 'bird tweet 鸟 推特' },
            { char: '🐔', keys: 'chicken 鸡' },
            { char: '🐷', keys: 'pig 猪' },
            { char: '🐮', keys: 'cow milk 牛 牛奶' },
            { char: '🐴', keys: 'horse 马' },
            { char: '🦄', keys: 'unicorn rare 独角兽 稀有' },
            { char: '🐺', keys: 'wolf 狼' },
            { char: '🦁', keys: 'lion 狮子' },
            { char: '🐯', keys: 'tiger 虎' },
            { char: '🐵', keys: 'monkey 猴' },
            { char: '🐶', keys: 'dog pet 狗 宠物' },
            { char: '🐱', keys: 'cat pet 猫 宠物' },
            { char: '🌍', keys: 'earth globe 地球 世界' },
            { char: '🌙', keys: 'moon night 月亮 夜晚' },
            { char: '☀️', keys: 'sunny day 太阳 晴' },
            { char: '🌤️', keys: 'partly sunny 多云' },
            { char: '⛅', keys: 'sun cloud 阴晴' },
            { char: '☁️', keys: 'cloud weather 云 天气' },
            { char: '🌧️', keys: 'rain 雨 降雨' },
            { char: '⛈️', keys: 'storm thunder 雷暴' },
            { char: '❄️', keys: 'snowflake freeze 雪花 冻结' },
            { char: '🌊', keys: 'wave water 波浪 水' },
            { char: '💧', keys: 'drop water 水滴' },
            { char: '🔥', keys: 'fire hot trend 火 热门' },
            { char: '🌈', keys: 'rainbow pride 彩虹' },
            { char: '✨', keys: 'sparkles new ai 闪光 精选 全新' },
            { char: '🌌', keys: 'milky way stars 星空 银河' },
        ],
    },
    {
        id: 'food',
        labelKey: 'folders.icon_category.food',
        entries: [
            { char: '☕', keys: 'coffee java tea drink 咖啡 饮品 茶' },
            { char: '🍵', keys: 'tea green 茶 抹茶' },
            { char: '🧋', keys: 'bubble tea 奶茶 珍珠' },
            { char: '🥤', keys: 'soda cup 汽水 饮料' },
            { char: '🧃', keys: 'juice box 果汁 盒装' },
            { char: '🥛', keys: 'milk 牛奶' },
            { char: '🍺', keys: 'beer 啤酒' },
            { char: '🍻', keys: 'cheers beers 干杯' },
            { char: '🍷', keys: 'wine red 红酒' },
            { char: '🥂', keys: 'champagne toast 香槟 庆祝' },
            { char: '🍸', keys: 'cocktail 鸡尾酒' },
            { char: '🍹', keys: 'tropical drink 热带饮品' },
            { char: '🍎', keys: 'apple red 苹果' },
            { char: '🍏', keys: 'green apple 青苹果' },
            { char: '🍌', keys: 'banana 香蕉' },
            { char: '🍇', keys: 'grapes 葡萄' },
            { char: '🍓', keys: 'strawberry 草莓' },
            { char: '🍉', keys: 'melon summer 西瓜 夏天' },
            { char: '🍊', keys: 'orange citrus 橙子' },
            { char: '🍋', keys: 'lemon 柠檬' },
            { char: '🍑', keys: 'peach 桃子' },
            { char: '🥝', keys: 'kiwi 猕猴桃' },
            { char: '🍅', keys: 'tomato 番茄' },
            { char: '🥑', keys: 'avocado 牛油果' },
            { char: '🌽', keys: 'corn 玉米' },
            { char: '🥦', keys: 'broccoli 西兰花' },
            { char: '🥕', keys: 'carrot 胡萝卜' },
            { char: '🍞', keys: 'bread toast 面包' },
            { char: '🥐', keys: 'croissant 可颂' },
            { char: '🥖', keys: 'baguette 法棍' },
            { char: '🧀', keys: 'cheese 奶酪' },
            { char: '🍚', keys: 'rice 米饭' },
            { char: '🍜', keys: 'noodles ramen 面条 拉面' },
            { char: '🍲', keys: 'pot stew 炖菜 火锅' },
            { char: '🍛', keys: 'curry rice 咖喱' },
            { char: '🍕', keys: 'pizza 披萨' },
            { char: '🍔', keys: 'burger 汉堡' },
            { char: '🍟', keys: 'fries 薯条' },
            { char: '🌮', keys: 'taco 塔可' },
            { char: '🍣', keys: 'sushi 寿司' },
            { char: '🥗', keys: 'salad healthy 沙拉 健康' },
            { char: '🍤', keys: 'shrimp tempura 炸虾' },
            { char: '🍰', keys: 'cake dessert 蛋糕 甜点' },
            { char: '🎂', keys: 'birthday cake 生日蛋糕' },
            { char: '🍦', keys: 'ice cream 冰淇淋' },
            { char: '🍩', keys: 'donut 甜甜圈' },
            { char: '🍪', keys: 'cookie 饼干' },
            { char: '🍫', keys: 'chocolate 巧克力' },
            { char: '🍬', keys: 'candy sweet 糖果' },
            { char: '🍯', keys: 'honey 蜂蜜' },
            { char: '🧂', keys: 'salt 盐' },
        ],
    },
    {
        id: 'status',
        labelKey: 'folders.icon_category.status',
        entries: [
            { char: '✅', keys: 'check done pass 完成 通过' },
            { char: '✔️', keys: 'heavy check ok 确认 对勾' },
            { char: '☑️', keys: 'checked box 已勾选' },
            { char: '❌', keys: 'cross fail no 失败 错' },
            { char: '✖️', keys: 'multiply x remove 删除 乘' },
            { char: '⚠️', keys: 'warning caution 警告 注意' },
            { char: '❗', keys: 'exclamation important 重要 感叹' },
            { char: '❕', keys: 'note hint 提示' },
            { char: '❓', keys: 'question help 疑问 问题' },
            { char: '❔', keys: 'maybe question 存疑' },
            { char: '💯', keys: 'hundred perfect 满分 一百' },
            { char: '⛔', keys: 'no entry forbidden 禁止' },
            { char: '🚫', keys: 'prohibited banned 禁用' },
            { char: '🔞', keys: 'age restriction 限制 成人' },
            { char: '🔴', keys: 'red dot todo 红点 待办 录制' },
            { char: '🟠', keys: 'orange dot doing 橙点 进行中' },
            { char: '🟡', keys: 'yellow dot pause 黄点 暂停' },
            { char: '🟢', keys: 'green dot online done 绿点 在线' },
            { char: '🔵', keys: 'blue dot info 蓝点 信息' },
            { char: '🟣', keys: 'purple dot experiment 紫点 实验' },
            { char: '🟤', keys: 'brown dot 棕点' },
            { char: '⚫', keys: 'black circle dark 黑点' },
            { char: '⚪', keys: 'white circle light 白点' },
            { char: '🔺', keys: 'up triangle rise 上三角 升' },
            { char: '🔻', keys: 'down triangle fall 下三角 降' },
            { char: '🔼', keys: 'up button 上' },
            { char: '🔽', keys: 'down button 下' },
            { char: '▶️', keys: 'play start 播放 开始' },
            { char: '⏸️', keys: 'pause 暂停' },
            { char: '⏹️', keys: 'stop 停止' },
            { char: '⏭️', keys: 'next skip 下一项' },
            { char: '⏮️', keys: 'previous 上一项' },
            { char: '🔝', keys: 'top arrow pin 置顶' },
            { char: '🔜', keys: 'soon 即将' },
            { char: '🔚', keys: 'end 结束' },
            { char: '🆗', keys: 'ok button 可以' },
            { char: '🆕', keys: 'new button 新增 新' },
            { char: '🆓', keys: 'free 免费' },
            { char: '🈵', keys: 'full 满' },
            { char: '🚸', keys: 'caution child 小心' },
            { char: '💤', keys: 'zzz idle 休眠 空闲' },
            { char: '🎉', keys: 'party popper done 庆祝 完成' },
            { char: '🎊', keys: 'confetti 彩球 庆祝' },
            { char: '📛', keys: 'name badge 名牌' },
            { char: '🔰', keys: 'beginner 新手' },
            { char: '⭕', keys: 'hollow circle 圆圈' },
            { char: '〰️', keys: 'wavy dash 波浪线' },
        ],
    },
    {
        id: 'symbols',
        labelKey: 'folders.icon_category.symbols',
        entries: [
            { char: '™️', keys: 'trademark brand 商标 品牌' },
            { char: '©️', keys: 'copyright 版权' },
            { char: '®️', keys: 'registered 注册商标' },
            { char: '#️⃣', keys: 'hash tag number 井号 话题' },
            { char: '*️⃣', keys: 'asterisk star 星号' },
            { char: '0️⃣', keys: 'zero keycap 数字 0' },
            { char: '1️⃣', keys: 'one keycap 数字 1' },
            { char: '2️⃣', keys: 'two keycap 数字 2' },
            { char: '3️⃣', keys: 'three keycap 数字 3' },
            { char: '4️⃣', keys: 'four keycap 数字 4' },
            { char: '5️⃣', keys: 'five keycap 数字 5' },
            { char: '6️⃣', keys: 'six keycap 数字 6' },
            { char: '7️⃣', keys: 'seven keycap 数字 7' },
            { char: '8️⃣', keys: 'eight keycap 数字 8' },
            { char: '9️⃣', keys: 'nine keycap 数字 9' },
            { char: '🔟', keys: 'ten keycap 数字 10' },
            { char: '➕', keys: 'plus add 加' },
            { char: '➖', keys: 'minus 减' },
            { char: '➗', keys: 'divide 除' },
            { char: '🟰', keys: 'equal 等于' },
            { char: '➰', keys: 'curly loop 花环' },
            { char: '➿', keys: 'double loop 双环' },
            { char: '❤️', keys: 'red heart love 爱心 喜欢' },
            { char: '🧡', keys: 'orange heart 橙心' },
            { char: '💛', keys: 'yellow heart 黄心' },
            { char: '💚', keys: 'green heart 绿心' },
            { char: '💙', keys: 'blue heart 蓝心' },
            { char: '💜', keys: 'purple heart 紫心' },
            { char: '🖤', keys: 'black heart 黑心' },
            { char: '🤍', keys: 'white heart 白心' },
            { char: '💔', keys: 'broken heart 心碎' },
            { char: '♦️', keys: 'diamond suit 方块' },
            { char: '♣️', keys: 'club suit 梅花' },
            { char: '♥️', keys: 'heart suit 红桃' },
            { char: '♠️', keys: 'spade suit 黑桃' },
            { char: '🀄', keys: 'red dragon mahjong 麻将' },
            { char: '🎴', keys: 'flower cards 花牌' },
            { char: '♨️', keys: 'hot springs 温泉' },
            { char: '💬', keys: 'speech bubble 对话 评论' },
            { char: '🗨️', keys: 'speech left 气泡' },
            { char: '💭', keys: 'thought bubble 想法 思考' },
            { char: '🔆', keys: 'brightness high 亮度' },
            { char: '🔇', keys: 'mute 静音' },
            { char: '📴', keys: 'phone off 关机' },
            { char: '🔘', keys: 'radio button 单选' },
            { char: '◻️', keys: 'white square 白方' },
            { char: '◼️', keys: 'black square 黑方' },
        ],
    },
];

export const EMOJI_ICON_ENTRIES: EmojiEntry[] = EMOJI_ICON_CATEGORIES.flatMap((category) => category.entries);

