/**
 * Loads every rule so the registry is complete before the first run.
 *
 * Each rule file exports a builder class and registers nothing by itself: this list is what turns a
 * builder into a rule, and it is the only place the 67 rule modules are named. The lint
 * engine is reached through a dynamic import everywhere else, so a reader who never opens the
 * linter never pays for the parse stack or the rule bodies.
 */
import AddBlankLineAfterYaml from './rules/add-blank-line-after-yaml';
import AlignTableColumns from './rules/align-table-columns';
import AutoCorrectCommonMisspellings from './rules/auto-correct-common-misspellings';
import BlockquoteStyle from './rules/blockquote-style';
import BlockquotifyOnPaste from './rules/blockquotify-on-paste';
import CapitalizeHeadings from './rules/capitalize-headings';
import CompactYaml from './rules/compact-yaml';
import ConsecutiveBlankLines from './rules/consecutive-blank-lines';
import ConvertBulletListMarkers from './rules/convert-bullet-list-markers';
import ConvertSpacesToTabs from './rules/convert-spaces-to-tabs';
import DedupeYamlArrayValues from './rules/dedupe-yaml-array-values';
import DefaultLanguageForCodeFences from './rules/default-language-for-code-fences';
import EmphasisStyle from './rules/emphasis-style';
import EmptyLineAroundBlockquotes from './rules/empty-line-around-blockquotes';
import EmptyLineAroundCodeFences from './rules/empty-line-around-code-fences';
import EmptyLineAroundHorizontalRules from './rules/empty-line-around-horizontal-rules';
import EmptyLineAroundMathBlock from './rules/empty-line-around-math-block';
import EmptyLineAroundTables from './rules/empty-line-around-tables';
import EscapeYamlSpecialCharacters from './rules/escape-yaml-special-characters';
import FileNameHeading from './rules/file-name-heading';
import FootnoteAfterPunctuation from './rules/footnote-after-punctuation';
import ForceYamlEscape from './rules/force-yaml-escape';
import FormatTagsInYaml from './rules/format-tags-in-yaml';
import FormatYamlArrays from './rules/format-yaml-arrays';
import HeaderIncrement from './rules/header-increment';
import HeadingBlankLines from './rules/heading-blank-lines';
import HeadingsStartLine from './rules/headings-start-line';
import InsertYamlAttributes from './rules/insert-yaml-attributes';
import LineBreakAtDocumentEnd from './rules/line-break-at-document-end';
import MoveFootnotesToTheBottom from './rules/move-footnotes-to-the-bottom';
import MoveInlineFieldsToYaml from './rules/move-inline-fields-to-yaml';
import MoveMathBlockIndicatorsToOwnLine from './rules/move-math-block-indicators-to-own-line';
import MoveTagsToYaml from './rules/move-tags-to-yaml';
import NoBareUrls from './rules/no-bare-urls';
import OrderedListStyle from './rules/ordered-list-style';
import ParagraphBlankLines from './rules/paragraph-blank-lines';
import PreventDoubleChecklistIndicatorOnPaste from './rules/prevent-double-checklist-indicator-on-paste';
import PreventDoubleListItemIndicatorOnPaste from './rules/prevent-double-list-item-indicator-on-paste';
import ProperEllipsisOnPaste from './rules/proper-ellipsis-on-paste';
import ProperEllipsis from './rules/proper-ellipsis';
import QuoteStyle from './rules/quote-style';
import ReIndexFootnotes from './rules/re-index-footnotes';
import RemoveConsecutiveListMarkers from './rules/remove-consecutive-list-markers';
import RemoveEmptyLinesBetweenListMarkersAndChecklists from './rules/remove-empty-lines-between-list-markers-and-checklists';
import RemoveEmptyListMarkers from './rules/remove-empty-list-markers';
import RemoveHyphenatedLineBreaks from './rules/remove-hyphenated-line-breaks';
import RemoveHyphensOnPaste from './rules/remove-hyphens-on-paste';
import RemoveLeadingOrTrailingWhitespaceOnPaste from './rules/remove-leading-or-trailing-whitespace-on-paste';
import RemoveLeftoverFootnotesFromQuoteOnPaste from './rules/remove-leftover-footnotes-from-quote-on-paste';
import RemoveLinkSpacing from './rules/remove-link-spacing';
import RemoveMultipleBlankLinesOnPaste from './rules/remove-multiple-blank-lines-on-paste';
import RemoveMultipleSpaces from './rules/remove-multiple-spaces';
import RemoveSpaceAroundCharacters from './rules/remove-space-around-characters';
import RemoveSpaceBeforeOrAfterCharacters from './rules/remove-space-before-or-after-characters';
import RemoveTrailingPunctuationInHeading from './rules/remove-trailing-punctuation-in-heading';
import RemoveYamlKeys from './rules/remove-yaml-keys';
import SortYamlArrayValues from './rules/sort-yaml-array-values';
import SpaceAfterListMarkers from './rules/space-after-list-markers';
import SpaceBetweenChineseJapaneseOrKoreanAndEnglishOrNumbers from './rules/space-between-chinese-japanese-or-korean-and-english-or-numbers';
import StrongStyle from './rules/strong-style';
import TrailingSpaces from './rules/trailing-spaces';
import TwoSpacesBetweenLinesWithContent from './rules/two-spaces-between-lines-with-content';
import UnorderedListStyle from './rules/unordered-list-style';
import YamlKeySort from './rules/yaml-key-sort';
import YamlTimestamp from './rules/yaml-timestamp';
import YamlTitleAlias from './rules/yaml-title-alias';
import YamlTitle from './rules/yaml-title';
import { registerRule, sortRules } from './rules';

registerRule(AddBlankLineAfterYaml.getRule());
registerRule(AlignTableColumns.getRule());
registerRule(AutoCorrectCommonMisspellings.getRule());
registerRule(BlockquoteStyle.getRule());
registerRule(BlockquotifyOnPaste.getRule());
registerRule(CapitalizeHeadings.getRule());
registerRule(CompactYaml.getRule());
registerRule(ConsecutiveBlankLines.getRule());
registerRule(ConvertBulletListMarkers.getRule());
registerRule(ConvertSpacesToTabs.getRule());
registerRule(DedupeYamlArrayValues.getRule());
registerRule(DefaultLanguageForCodeFences.getRule());
registerRule(EmphasisStyle.getRule());
registerRule(EmptyLineAroundBlockquotes.getRule());
registerRule(EmptyLineAroundCodeFences.getRule());
registerRule(EmptyLineAroundHorizontalRules.getRule());
registerRule(EmptyLineAroundMathBlock.getRule());
registerRule(EmptyLineAroundTables.getRule());
registerRule(EscapeYamlSpecialCharacters.getRule());
registerRule(FileNameHeading.getRule());
registerRule(FootnoteAfterPunctuation.getRule());
registerRule(ForceYamlEscape.getRule());
registerRule(FormatTagsInYaml.getRule());
registerRule(FormatYamlArrays.getRule());
registerRule(HeaderIncrement.getRule());
registerRule(HeadingBlankLines.getRule());
registerRule(HeadingsStartLine.getRule());
registerRule(InsertYamlAttributes.getRule());
registerRule(LineBreakAtDocumentEnd.getRule());
registerRule(MoveFootnotesToTheBottom.getRule());
registerRule(MoveInlineFieldsToYaml.getRule());
registerRule(MoveMathBlockIndicatorsToOwnLine.getRule());
registerRule(MoveTagsToYaml.getRule());
registerRule(NoBareUrls.getRule());
registerRule(OrderedListStyle.getRule());
registerRule(ParagraphBlankLines.getRule());
registerRule(PreventDoubleChecklistIndicatorOnPaste.getRule());
registerRule(PreventDoubleListItemIndicatorOnPaste.getRule());
registerRule(ProperEllipsisOnPaste.getRule());
registerRule(ProperEllipsis.getRule());
registerRule(QuoteStyle.getRule());
registerRule(ReIndexFootnotes.getRule());
registerRule(RemoveConsecutiveListMarkers.getRule());
registerRule(RemoveEmptyLinesBetweenListMarkersAndChecklists.getRule());
registerRule(RemoveEmptyListMarkers.getRule());
registerRule(RemoveHyphenatedLineBreaks.getRule());
registerRule(RemoveHyphensOnPaste.getRule());
registerRule(RemoveLeadingOrTrailingWhitespaceOnPaste.getRule());
registerRule(RemoveLeftoverFootnotesFromQuoteOnPaste.getRule());
registerRule(RemoveLinkSpacing.getRule());
registerRule(RemoveMultipleBlankLinesOnPaste.getRule());
registerRule(RemoveMultipleSpaces.getRule());
registerRule(RemoveSpaceAroundCharacters.getRule());
registerRule(RemoveSpaceBeforeOrAfterCharacters.getRule());
registerRule(RemoveTrailingPunctuationInHeading.getRule());
registerRule(RemoveYamlKeys.getRule());
registerRule(SortYamlArrayValues.getRule());
registerRule(SpaceAfterListMarkers.getRule());
registerRule(SpaceBetweenChineseJapaneseOrKoreanAndEnglishOrNumbers.getRule());
registerRule(StrongStyle.getRule());
registerRule(TrailingSpaces.getRule());
registerRule(TwoSpacesBetweenLinesWithContent.getRule());
registerRule(UnorderedListStyle.getRule());
registerRule(YamlKeySort.getRule());
registerRule(YamlTimestamp.getRule());
registerRule(YamlTitleAlias.getRule());
registerRule(YamlTitle.getRule());

sortRules();

export { rules, rulesDict, ruleTypeToRules, RuleType } from './rules';
export { RuleBuilderBase } from './rule-builder';
